### ISSUE TITLE
How to installed all policies into our datacenter instead of GitHub on internet

### ISSUE THREAD

**Issue by jainpratik163** [datreeio/datree#149]
**Is your feature request related to a problem? Please describe.**

currently, we install date binary on Unix and if we want to change policy then we need to login to datree site and do changes and also we are not allowed to use the internet in that case how we can do.
how we can do all setup on-prem hardware.

**Comment by eyarz** [comment]
The good news is that we are going to release [Policy-as-Code ](https://github.com/datreeio/datree/issues/127) soon, so you will not need to log in to change your policies setup, you will be able to do it via code.

The bad news is that datree can't work in an [air-gapped environment](https://github.com/datreeio/datree/issues/87), you need to have an internet connection because of the "centralized policy" concept. We have this on our roadmap but it will take some time (~3 months) until it will be ready.

**Comment by jainpratik163** [comment]
some customers don't allow us to use the internet in that case how we can use it.
is there any way that we can install this at the organizational level and use it?

**Comment by eyarz** [comment]
No, sorry, you need to have an internet connection for Datree to work.
What are the key features that Datree has and you need?
Based on your answer, I will be able to recommend alternative tools that are also compatible with an air-gapped environment.

**Comment by jainpratik163** [comment]
during CI we want to check all k8s YAML files and helm charts also if they are proper and correct or not.

**Comment by eyarz** [comment]
From my experience, [Conftest](https://www.conftest.dev/) is also a great project and can help you with that. 
They also have a [Helm plugin](https://github.com/instrumenta/helm-conftest) (like ours).

**Comment by jainpratik163** [comment]
Thanks for the suggestion I will check that one.
But if we can this feature that will also great.
