### ISSUE TITLE
Non strict mode - ignore files are not k8s files

### ISSUE THREAD

**Issue by romanlab** [datreeio/datree#187]
**Is your feature request related to a problem? Please describe.**

when a user has several files (e.g. "user_configs.yaml") in a dir that not all of them are K8s files and he runs datree on the entire dir content, he will get errors (not valid yaml/k8s file check will fail) on those files.

**Describe the solution you'd like**

add a flag that will ignore files that are not K8s files.
we can do that by checking for mandatory properties such as "apiVersion" or "kind".

**Comment by romanlab** [comment]
@dimabru per your design:

Add `--not-strict` flag:

1. ignore all files that are not yaml / wannabe k8s files

2. display yaml validation step - always pass

3. at the end - only show files passed [1]

4. exist code depends on [3]

**Comment by eyarz** [comment]
I gave it some thought, and I'm not sure this is the best name for this flag.
maybe it needs to be `--ignore-other-files` \ `--filter "not k8s files"` \ something else?

**Comment by romanlab** [comment]
How about `--skip-invalid-files` or `ignore-invalid-files` ?

**Comment by eyarz** [comment]
but those files are valid, they are just not valid k8s files...
maybe `--skip/ignore-invalid-manifests` ?

**Comment by dimabru** [comment]
`ignore-invalid-manifests` (or other similar flag names) suggests that we should also ignore files that are supposed to fail the k8s schema validation step for not passing a specific schema, which is something we still want to keep when using this type of flag.

I think using the approach _what is in_ is better than _what is out_. IMO the flag should describe the types of files we **are** validating rather than describing what is not considered valid.

so maybe one of: `--only-k8s` | `--non-strict-k8s` ?

**Comment by eyarz** [comment]
sounds good to me:
`datree test *.yaml --only-k8s-files`
