### ISSUE TITLE
Invalid namespace file passes Datree validation

### ISSUE THREAD

**Issue by jobinjosem1** [datreeio/datree#220]
apiVersion: v1
kind: Namespace
metadata:
creationTimestamp: null
name: Test2
spec: {}
status: {}

Trying to validate a namespace YAML file that has an invalid name.
If I apply the above file with the dry-run=server flag it throws an error "The Namespace "Test2" is invalid: metadata.name: Invalid value: "Test2": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name', or '123-abc', regex used for validation is 'a-z0-9?')" 

but datree test doesn't detect this as an error.

**Comment by eyarz** [comment]
Yes, you're right, this is an issue, but it's not a bug. I will explain what I mean :)
What you describe, should fail during the schema validation step (`[X] Kubernetes schema validation`).

The problem is that the namespace validation (and some other validations) are not part of the official K8s JSON Schema definition. It's part of a different validation process that is happening before applying resources to the cluster.
This is why when I run `--dry-run=client` it will not fail:
![image](https://user-images.githubusercontent.com/19731161/138240100-10d7fd6f-f78f-4e04-893d-7e560141976f.png)

Now that we understand why it's not a bug, there are two options:
1) we will add it as a built-in rule to our system (we have something similar for [labels](https://hub.datree.io/ensure-labels-value-valid)) but then you will need to wait until it will be prioritized by us.
2) you can create a [custom rule](https://hub.datree.io/custom-rules-overview) by yourself to check this logic. JSON Schema engine actually has built-in support for the RFC-1123 standard or you can use a regex for that - `^(?!((^[a-z0-9A-Z]{1,61}([a-z0-9A-Z]|-|_|\\.){0,61}[a-z0-9A-Z]$)|(^[a-z0-9A-Z]$))).*$` 

If you choose to go with option 2, let me know if you need any help with creating the custom rule.
