### ISSUE TITLE
Docker image missing tag versions

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#250]
**Is your feature request related to a problem? Please describe.**
Datree's docker image doesn't include old versions, only the latest
![image](https://user-images.githubusercontent.com/19731161/139341921-bbc69776-c5c8-456e-be94-f164ffbce978.png)

**Describe the solution you'd like**
A dedicated image tag version for each CLI release 

**Additional context**
Related to https://github.com/datreeio/datree/pull/225

**Comment by kevholmes** [comment]
Something to consider is that GitHub includes its own [container image repository](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) now for public projects with no rate limiting. I do not believe GitHub has any [pull limits](https://www.docker.com/increase-rate-limits) as Dockerhub has recently implemented. I find this pretty important for CI type apps since they usually are included in jobs that get executed a lot! This container build process is probably in Travis right now, but if you wanted to move it into Actions I could certainly help with that.

**Comment by eyarz** [comment]
@dimabru WDYT?

**Comment by eyarz** [comment]
because docker hub is still the default registry, I think that users will expect that we will have an image there.
having said that, we can **also** publish the docker images to the GH registry.

on docker hub you can configure to "pull" new releases and create a new tag (from docker hub side), instead of "pushing" a new docker image with code. Do you know if this is possible also with GH registry?
We think it's better this way because it's not creating a dependency (e.g. if GH registry is down it will not stop the build)

**Comment by kevholmes** [comment]
Hey @eyarz is [this](https://docs.docker.com/docker-hub/builds/) what you're referring to when you say DockerHub will pull a new release and create a tag? It is also essentially what GH Actions can be configured to do - an event (like creating a new release tag prefixed by the letter `v`) or a push to a special branch (or both) in the datree repo can trigger an Action workflow that would pull the source, build an image and push it to any number of container registries you decide upon.

Ultimately I would recommend building the image once and syncing it to it many places, rather than having it build in Dockerhub and Actions separately and pushed to their own repos. Each build environment could be slightly different and lead to some oddities that could get hard to track down or debug if a user is having a problem. You'd also have to maintain that build process in two different places (Dockerhub and Actions) which seems less than ideal for a small team working on a growing project like datree.

**Comment by romanlab** [comment]
> Hey @eyarz is [this](https://docs.docker.com/docker-hub/builds/) what you're referring to when you say DockerHub will pull a new release and create a tag? It is also essentially what GH Actions can be configured to do - an event (like creating a new release tag prefixed by the letter `v`) or a push to a special branch (or both) in the datree repo can trigger an Action workflow that would pull the source, build an image and push it to any number of container registries you decide upon.
> 
> Ultimately I would recommend building the image once and syncing it to it many places, rather than having it build in Dockerhub and Actions separately and pushed to their own repos. Each build environment could be slightly different and lead to some oddities that could get hard to track down or debug if a user is having a problem. You'd also have to maintain that build process in two different places (Dockerhub and Actions) which seems less than ideal for a small team working on a growing project like datree.

That sounds good. We do have a few restrictions for the process:

1. We want to push to docker hub(as well as other registries)
2. We want the workflow to not be a blocker. That is, if the push fails we still want the rest of the build to continue(build and release of the binary)

**Comment by kevholmes** [comment]
> 
> That sounds good. We do have a few restrictions for the process:
> 
>     1. We want to push to docker hub(as well as other registries)
> 
>     2. We want the workflow to not be a blocker. That is, if the push fails we still want the rest of the build to continue(build and release of the binary)

1. That should be ok. If you'd like to use Dockerhub you'll need to create a GitHub Secret with credential information for Dockerhub. You could let me know what the names of the secrets are for instance DOCKERHUB_USERNAME and DOCKERHUB_TOKEN which I could then plug into an Actions workflow. We shouldn't need credentials for GitHub's ghcr.io container repo as I believe the GITHUB_TOKEN given to an Actions workflow is scoped already to do that.

2. That shouldn't be an issue if we're using Actions to build the images. Looking at your existing workflows I see `release.yml` which appears to be a manually triggered workflow. We could ensure that the first job in that file `release` is successful and if so, we then build our docker image and push out to whatever container repos you'd like.

**Comment by dimabru** [comment]
hi @kevholmes,
I added the keys to datree repo secrets: `DOCKERHUB_USERNAME`, `DOCKERHUB_TOKEN`
I like your suggested solution. Adding a workflow post-release will be a good point for the docker deployment, that way even if it fails it will not block the release process.
Thanks for taking this

**Comment by kevholmes** [comment]
> hi @kevholmes, I added the keys to datree repo secrets: `DOCKERHUB_USERNAME`, `DOCKERHUB_TOKEN` I like your suggested solution. Adding a workflow post-release will be a good point for the docker deployment, that way even if it fails it will not block the release process. Thanks for taking this

Awesome! I'll get started on it.
