### ISSUE TITLE
Releases don't show complete changelog

### ISSUE THREAD

**Issue by royhadad** [datreeio/datree#257]
**Describe the bug**
In Releases page: https://github.com/datreeio/datree/releases you don't see the full changelog between the current and previous release

**To Reproduce**
Go to releases page: https://github.com/datreeio/datree/releases

**Expected behavior**
in a release, see the full changelog

**Screenshots**
![Screen Shot 2021-10-31 at 13 38 19](https://user-images.githubusercontent.com/39004075/139581206-87d10171-ec0a-47b8-833c-8f1220e533bb.png)

**Desktop (please complete the following information):**
 - OS: not relevant

**Datree version (run `datree version`):**
 - Version: not relevant

**Comment by noaabarki** [comment]
Good catch @royhadad, I think this is very important. The way I see it, we want each release candidate to display in its changelog all the "new history" it contains, but not since the previous one but since the last release. For example, if we have released `1-RC` and immediately after we released `2-RC` we want the `2-RC` release changelog to include `1-RC` changelog.

**Comment by dimabru** [comment]
This is still relevant
