### ISSUE TITLE
Curl install fails in MacOS

### ISSUE THREAD

**Issue by adifayer** [datreeio/datree#368]
**Describe the bug**
Curl install fails in MacOS 

**To Reproduce**
1. Verify datree is not installed (inc. hidden files) in a computer w/ mac OS
2. Run datree curl install
3. See error

**Expected behavior**
Datree files and folders are created

**Screenshots**
![image](https://user-images.githubusercontent.com/43816136/148242400-4f15c14e-4ca4-4a0c-815d-9053cd5bae80.png)

**Comment by dimabru** [comment]
This issue happens for users that don't have `/usr/local/bin` on their local environment when installing datree.
A good way of fixing it would be to modify the `install.sh` script to create `/usr/local/bin` directory if it doesn't exist before copying `datree` executable to that location

**Comment by royhadad** [comment]
@dimabru Does this problem occur on linux/windows as well? or only mac?

**Comment by dimabru** [comment]
@royhadad Good question. I'm not sure. Stands to reason that if the user decides to manually delete the folder `/usr/local/bin` in a linux machine the script will behave the same way.

Regardless, I think the solution should be problem focused rather than environment focused. Meaning we should not assume a folder exists before writing to it, disregarding the operating system
