### ISSUE TITLE
Validate test command flags before start evaluation

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#380]
**Describe the solution you'd like**

Validate test command flags before starting evaluation.

**Requirements** 
Golang basic level.

**“How to implement” Suggestion**
Add validation method to `TestCommandFlags` :: `func (flags *TestCommandFlags) Validate(cmd *cobra.Command, args []string) error`. This method should validate the flags of the commands, for example: `-o output` flag is valid if its one of `simple, xml, json, yaml`. Eventually, in my mind I had something like this:

```go
cmd := &cobra.Command{
		...
		Run: func(cmd *cobra.Command, args []string) {
			...
			err := flags.Validate(cmd, args)
			// handle err
		},
	}
```

**Comment by Abhra303** [comment]
I would like to try this.

**Comment by noaabarki** [comment]
Hey @Abhra303! Amazing, you got it! If you have any question, don't hesitate to reach out :)

**Comment by Abhra303** [comment]
Hello @noaabarki ,

Here we have just to validate these three flags - 1) `output` (2) `policy` and (3) `schema-locations` right? Because, `ignore-missing-schemas` and `only-k8s-files` are of boolean type and there exists a validation function for `schema-version` already which is `validateK8sVersionFormatIfProvided`.

**Comment by noaabarki** [comment]
Hey @Abhra303, yes, regarding `ignore-missing-schemas` and `only-k8s-files` flags, I believe Cobra already got it covered for us with all the validation we need. Definitely use `validateK8sVersionFormatIfProvided` function, good job!  Overall, make sure to add test-cases for all the flags.

**Comment by Abhra303** [comment]
Hello @noaabarki 

I am facing some challenges for validating `policy` and `schema-location` - 

- I didn't find any way to know the available policy names. So, I can't check whether the value given to `policy` is valid or not. Am I missing something here?
- According to [this](https://github.com/yannh/kubeconform#overriding-schemas-location---crd-and-openshift-support),  `schema-location` can accept http(s) urls or local file-system-path. It can also take "default". If the given value has no `.json` at the end, `Kubeconform` will assume that filenames / a file structure is identical to that of `github.com/yannh/kubernetes-json-schema`. If `.json` exists at the end of the value, it assumes the value is a Go templated string that indicates how to search for JSON schemas. So, I was planning to make a regex expression to verify that the value is one of the above mentioned types (http(s) or file-path or default). Now, the problem is not all the urls or file-paths are valid for `schema-location`. For example `https://google.com` is not a valid `schema-location` value. So, could you please give me suggestion about how to deal with it?

**Comment by noaabarki** [comment]
Hi @Abhra303, 

- Regrading `policy`, I believe there's no need to validate if the provided policy name is available. Our backend is responsible for that and it already contains this logic. 
- Regarding the `schema-location`, IMHO the validation you described above is great and powerful but it's should be handled in Kubeconform (consider submitting them a PR, really 😊). From our side, any input for `schema-location` will be valid so you can drop the validation on that flag. 

Fantastic job though, awesome to have you with us 😎

**Comment by Abhra303** [comment]
thanks @noaabarki , I am pleased to contribute here :)
