### ISSUE TITLE
datree should fail when receiving empty files

### ISSUE THREAD

**Issue by myishay** [datreeio/datree#390]
**Describe the bug**
datree is returning zero code after receiving an empty file from stdin

**To Reproduce**
1. Run command 'echo "" | datree test -'
2. datree returns with zero exit code

**Expected behavior**
datree fails with nonzero exit code

**Screenshots**
![Screen Shot 2022-01-19 at 10 26 54](https://user-images.githubusercontent.com/22665577/150092656-7442799d-3fce-42fd-a638-da622547fda6.png)

**Desktop (please complete the following information):**
 - OS: Darwin

**Datree version (run `datree version`):**
 - Version: 0.15.0

**Additional context**  
Related to https://github.com/datreeio/datree/issues/213 except that here the empty file comes from stdin

**Comment by eyarz** [comment]
This happens also when passing an empty file to Datree.
**Expected behavior:** fail schema validation step

**Comment by dimabru** [comment]
Looks like this only happens when using `echo`

Here's an execution example of an empty file. Fails schema validation step for me (version 0.15.0)

![image](https://user-images.githubusercontent.com/25605786/150150761-6690ac86-2b1e-45f8-b01d-b1f581f783de.png)

Another example piping an empty file

![image](https://user-images.githubusercontent.com/25605786/150151118-5a9fd6b2-550b-4d8c-a503-aaf89657e3bc.png)

**Comment by eyarz** [comment]
@royhadad helped me to understand that it happened to me because I had an empty line in my empty file.
This use case should also be handled as an empty file...
WDYT?

**Comment by royhadad** [comment]
**before my change** - if there is 1 result in the status is empty => return failure for k8s validation
**after my change** - if all of the results have status empty => return failure for k8s validation (ignore empty configs as long as not all of them are empty)
