### ISSUE TITLE
Running test on non k8s yaml files with `--only-k8s-files` flag raises an error

### ISSUE THREAD

**Issue by TzlilSwimmer123** [datreeio/datree#430]
**Describe the bug**
Running `datree test` on non k8s files with `--only-k8s-files` flag raises invalid memory address or nil pointer dereference error on runtime

**To Reproduce**
1. Run command 'datree test internal/fixtures/kube/Chart.yaml --only-k8s-files'
2. See error

**Expected behavior**
Suppose to show test results - this file/these files should be presented with their invalidation error

**Screenshots**
<img width="886" alt="Screen Shot 2022-02-23 at 12 29 38" src="https://user-images.githubusercontent.com/51244810/155301989-10c8bc10-4624-4104-9c59-2b423a072672.png">

**Desktop (please complete the following information):**
 - OS: macOs Monterey
 
**Datree version:**
 - Version: 0.15.22

**Comment by royhadad** [comment]
After some investigation, I found that this happens because of this line:
https://github.com/datreeio/datree/blob/34815cb824e4ef8b205c322bbf7d727228898876/cmd/test/main.go#L405
![Screen Shot 2022-03-09 at 17 18 42](https://user-images.githubusercontent.com/39004075/157471556-0c4c02f0-ac22-4a8d-bf86-dcfea2786f51.png)
 
 results.EvaluationResults is equal to null, which causes a runtime error
