### ISSUE TITLE
datree suddenly does not show the dashboard link with the token.

### ISSUE THREAD

**Issue by angelwcrypto** [datreeio/datree#566]
**Describe the bug**
datree suddenly does not show the dashboard link with the token.
   ~ ❯ datree test ~/.datree/k8s-demo.yaml                                                                               12s
>>  File: .datree/k8s-demo.yaml

[V] YAML validation
[V] Kubernetes schema validation

[X] Policy check

❌  Ensure each container has a configured memory limit  [1 occurrence]
    — metadata.name: rss-site (kind: Deployment)
💡  Missing property object `limits.memory` - value should be within the accepted boundaries recommended by the organization

❌  Ensure workload has valid label values  [1 occurrence]
    — metadata.name: rss-site (kind: Deployment)
💡  Incorrect value for key(s) under `labels` - the vales syntax is not valid so the Kubernetes engine will not accept it

❌  Ensure each container has a configured liveness probe  [1 occurrence]
    — metadata.name: rss-site (kind: Deployment)
💡  Missing property object `livenessProbe` - add a properly configured livenessProbe to catch possible deadlocks

❌  Ensure each container image has a pinned (tag) version  [1 occurrence]
    — metadata.name: rss-site (kind: Deployment)
💡  Incorrect value for key `image` - specify an image version to avoid unpleasant "version surprises" in the future

(Summary)

- Passing YAML validation: 1/1

- Passing Kubernetes (1.19.0) schema validation: 1/1

- Passing policy check: 0/1

+-----------------------------------+-----------------------+
| Enabled rules in policy “Default” | 21                    |
| Configs tested against policy     | 1                     |
| Total rules evaluated             | 21                    |
| Total rules failed                | 4                     |
| Total rules passed                | 17                    |
| See all rules in policy           | https://hub.datree.io |
+-----------------------------------+-----------------------+

**To Reproduce**
1. Run command '...'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]

**Datree version (run `datree version`):**
 - Version: 1.2.0

**Client ID (`cat ~/.datree/config.yaml`):**
   ~ ❯ cat ~/.datree/config.yaml                                                                                          3s
client_id: iZA8c9amFLKMdrWjY5mXw3
offline: fail

**Additional context**  
default k8s-demo.yaml

**Comment by royhadad** [comment]
I believe this change is on purpose, and happens for users that are already signed in.
To access the dashboard, simply go to app.datree.io and login to your account

**Comment by adifayer** [comment]
Although the token is used to pull the policy from your dashboard, we wanted to make sure that no one uses it on your behalf, therefore we implemented this change in the CLI output. 
You can find all of your tokens in the dashboard- https://app.datree.io/settings/token-management

**Comment by redgra0315** [comment]
[Web Application Interface](https://hub.datree.io/centralized-policy/#utm_source=github&utm_medium=organic_oss)
Whether the Web Application can be accessed only on the public network and whether the Web Application can be used on the Intranet of the company

**Comment by eyarz** [comment]
@redgra0315 as you can see from the [architecture](https://github.com/datreeio/datree#%EF%B8%8F-architecture), the GUI ([Web Application Interface](https://hub.datree.io/centralized-policy/#utm_source=github&utm_medium=organic_oss)), can only be accessed on the public network.

**Comment by DannyBen** [comment]
This also confused me. I mean, it is perfect that the link is shortened after a token is configured, but this line in the output looks like a mistake:

```
| See all rules in policy | https://hub.datree.io/ |
```

Why point to the documentation site rather than to https://app.datree.io/ - especially since hub.datree.io does not have a "sign in" link. If providing only one link, I believe it should be to the app site and not documentation site.

**Comment by royhadad** [comment]
I tend to agree with @DannyBen, WDYT? @adifay

**Comment by eyarz** [comment]
@royhadad @DannyBen The reason we don't link to the app (https://app.datree.io/) is that we don't want to confuse users with tokens that are connected to another account. Because we don't have a user management system (yet 😉), those users will click on the link and will create a new account for them, instead of connecting them to the token owner account.

Until this feature (user management) will be released, I think the best solution will be to add a [signin link](https://github.com/datreeio/docs/issues/24) to our docs and change the text to be correct (only to signup users) - something like: 
``| Check docs for more info | https://hub.datree.io/ |``
