### ISSUE TITLE
Severity level badge on policies UI

### ISSUE THREAD

**Issue by l2D** [datreeio/datree#676]
**Is your feature request related to a problem? Please describe.**
- I don't know which policy is in what severity.

**Describe the solution you'd like**
- Add severity badge after info badge.
e.g.
![2022-06-09_18-56-15_CjiFFo8j](https://user-images.githubusercontent.com/20911264/172841701-088d05a2-2f2e-4a53-8f96-186c44b6ddee.png)

**Describe alternatives you've considered**
- Add a column for severity level before category column

**Additional context**
n/a

**Comment by eyarz** [comment]
@l2D that is a good idea, but I think the challenge is to agree what will be the logic of deciding about the severity level.
With the CVE, it is easy because MIRTE already curates them, but what about the rest?
For example,  the rule [ensure each container image has a digest tag](https://hub.datree.io/built-in-rules/ensure-digest-tag) - is the severity high or medium? maybe it's low? 🤷‍♂️ IDK
and that's the problem - the severity is subjective and not objective (like CVEs).
WDYT?

*BTW, I like the extra effort you took with creating the UI mockup for this ;)

**Comment by l2D** [comment]
@eyarz, I agree with you. My point is just wanting some things to tell me to consider which I should enable or just optional.

**Comment by eyarz** [comment]
we identified that the problem is that when a new user sees the dashboard for the first time, it's hard to understand which of the rules he should enable/disable.

Therefore, we will create an automated way for users the generate relevant policies based on their own needs.
