### ISSUE TITLE
The --only-k8s-files flag is not working properly

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#704]
When using "--only-k8s-files" the relevant files are indeed ignored but they are still counted in the summary.

**Steps to reproduce the behavior:**
1. Put a non-k8s yaml in a directory.
2. cd into that directory, then run "datree test *.yaml --only-k8s-files"
3. The file will not be tested but will still appear in the summary (0/1)

**Expected behavior**
Files that are not tested should not appear in the summary count.

Tested with CLI version 1.5.20.

**Comment by amustaque97** [comment]
Hi @hadar-co, I couldn't understand the problem statement correctly.  According to me, the non-k8 file should also come as a part of the summary because the summary should show all the details even the non-k8 file. Generally summary should include both positive and negative details. 

![Screenshot 2022-07-03 at 9 09 53 PM](https://user-images.githubusercontent.com/21127788/177047010-6eef6d30-eadd-4d0d-9877-e011c53dbfe5.png)

On the left side of the screenshot, summary is showing the correct result: 
1. I passed only a single file to test.
2. k8 schema validation failed.
3. passing the policy check is not positive since it is an empty YAML file.

On the other hand, I executed `./datree test internal/fixtures/kube/k8s-demo.yaml --only-k8s-files` and in that k8 schema validation is passing/positive.  Yaml validation we have to do for all the files, we cannot ignore. Passing policy is dependent on the yaml file content. So I couldn't understand what is wrong here in the summary output.

Thank you

**Comment by hadar-co** [comment]
Hi @amustaque97, thanks for the detailed response:)
Both approaches are valid, however we discussed it and decided to exclude non-k8s files from the summary, for 2 reasons:
1. By using the flag, the user is explicitly stating that he/she is not interested in non-k8s files for this policy check, so only yaml validation is irrelevant for them.
2. This prevents redundant data in the output and makes it and the summary more concise and clear.

Hadar

**Comment by amustaque97** [comment]
> so only YAML validation is irrelevant for them

If I understand it correctly, we can remove the `Passing YAML validation` statement from the summary and its relevant changes in case of "datree test *.yaml --only-k8s-files"

Correct me if I'm wrong.

**Comment by hadar-co** [comment]
I don't think we should remove the statement, because even when specifying the "--only-k8s-files" flag, k8s files can still be non-valid yamls, so we need to check for that like we always do.
We only need to ignore the non-k8s files when writing the summary, because they are not relevant to the policy check.

For example, say you're testing a folder with 2 k8s YAMLs, and 1 non-k8s YAML, currently the summary will show that 3 files were tested (regardless of how many validations succeeded/failed).
What it should say in this case is 2 files.

Hope that was clearer:)

**Comment by amustaque97** [comment]
Probably I can take this up. By this weekend I will try to submit a pr. Please assign this issue to me. 🙂
