### ISSUE TITLE
Text unreadable on light background

### ISSUE THREAD

**Issue by meain** [datreeio/datree#709]
**Describe the bug**
Some text is unreadable on white background.

**To Reproduce**
1. Run command 'datree test <file>'

**Expected behavior**
Readable text

**Screenshots**

![2022-07-05-22-15-03](https://user-images.githubusercontent.com/14259816/177376922-7e4dbe5b-a92d-447d-b14c-212445dde96d.png)

We have things like `(summary)` etc in there which is not visible in the original screenshot.
![2022-07-05-22-19-35](https://user-images.githubusercontent.com/14259816/177377508-cb357b8a-50c5-4138-bd92-1b9f2a54b094.png)

**Desktop (please complete the following information):**
 - OS: Ubunto

**Datree version (run `datree version`):**
 - Version: 0.15.22

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: [e.g. FxYzfp3xFc2mZjNmLgcoGV]

**Additional context**  

Seems like hard coding `White` for color (for eg in https://github.com/datreeio/datree/blob/38c5fb3cc5b89148f2edcdb49d8b9dd1aab17aaf/pkg/printer/printer.go#L254) is causing issues.

**Comment by myishay** [comment]
Hi @meain, You pin pointed the place where the issue is! 🎯

The way I see it there are 2 possible solutions:
1. detect the terminal color where the CLI runs and change the theme colors according to that (don't know if it is possible, though I did manage to get the background color of my terminal using the command `\e]11;?\a`, taken from [this SO question](https://stackoverflow.com/questions/2507337/how-to-determine-a-terminals-background-color)).
2. make the `p.Theme.Colors.White` use the default color of the terminal and just making it bold (since we still want the `(Summary)`, `[1 occurrence]` etc. be more significant than the other prints).

@meain would you like to take it?

**Comment by meain** [comment]
> detect the terminal color where the CLI runs and change the theme colors according to that (don't know if it is possible, though I did manage to get the background color of my terminal using the command \e]11;?\a, taken from [this SO question](https://stackoverflow.com/questions/2507337/how-to-determine-a-terminals-background-color)).

I was not aware of something like that. I am not sure how the support is though, I tried it out it two terminal emulators (sakura, gnome-terminal) and neither of them gave me a response back. Even if they did, I think computing if we should use light or dark might still be messy.

> make the p.Theme.Colors.White use the default color of the terminal and just making it bold (since we still want the (Summary), [1 occurrence] etc. be more significant than the other prints).

This sounds like a good option IMO. Also, most terminal emulators enable something like "use bright colors for bold text" which should also give the bright text in most cases. I don't mind dropping a PR for this, but might take a little while before I get to it.

**Comment by myishay** [comment]
> This sounds like a good option IMO. Also, most terminal emulators enable something like "use bright colors for bold text" which should also give the bright text in most cases. I don't mind dropping a PR for this, but might take a little while before I get to it.

Sounds good, go for it!
